const state={currentDate:null,card:null,door:'suggested',zoom:1};
const views={journal:'journalView',atlas:'atlasView',alchemy:'alchemyView',method:'methodView'};
const fallbackCards={'2026-08-30':{suggested:{movement:'Present',lens:'Identity & Authenticity',depth:'🌿 Gentle',format:'Observation',question:"When I don't need to explain, improve, perform, or make sense of myself, what parts of me naturally take up space?"},gentler:{question:'What feels distinctly mine today, even if it is small, ordinary, or difficult to explain?'},different:{lens:'Joy, Pleasure & Curiosity',question:'What have I wanted to learn, notice, collect, watch, read, or explore lately simply because it interests me?'},wildcard:{format:'Curiosity Map',question:'Start with one thing you like. Follow each association wherever it goes until the trail naturally stops.'},freewrite:{question:'What has my attention today?'}}};
function localIsoDate(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function niceDate(iso){return new Date(`${iso}T12:00:00`).toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}
function parsePromptMarkdown(md){const clean=s=>s.replace(/^>\s*\*\*?|\*\*$/g,'').replace(/^>\s*/,'').trim();const section=name=>{const m=md.match(new RegExp(`## ${name}\\n([\\s\\S]*?)(?=\\n## |\\n### |$)`,'i'));return m?m[1].trim():''};const sb=section('Suggested Prompt');const field=(label,txt=sb)=>{const m=txt.match(new RegExp(`\\*\\*${label}:\\*\\*\\s*([^\\n]+)`,'i'));return m?m[1].trim():''};const quoted=txt=>{const line=txt.split('\n').find(l=>l.trim().startsWith('>'));return line?clean(line):''};const gb=section('🌿 Gentler'),db=section('🔀 Different Direction'),fm=section('🪶 Freewrite');const wm=md.match(/## 🎲 Wildcard(?:\s*[—-]\s*([^\n]+))?\n([\s\S]*?)(?=\n## |\n### |$)/i);return{suggested:{movement:field('Movement'),lens:field('Lens'),depth:field('Depth'),format:field('Format'),question:quoted(sb)},gentler:{question:quoted(gb)},different:{lens:field('Lens',db),question:quoted(db)},wildcard:{format:wm?.[1]?.trim()||'Wildcard',question:wm?quoted(wm[2]):''},freewrite:{question:quoted(fm)||'What has my attention today?'}}}
async function loadCard(iso){if(fallbackCards[iso])return fallbackCards[iso];const r=await fetch(`prompts/2026/${iso}.md`,{cache:'no-store'});if(!r.ok)throw new Error('Prompt not found');return parsePromptMarkdown(await r.text())}
function chip(text,type){const s=document.createElement('span');s.className=`meta-chip ${type}`;s.textContent=text;return s}
function renderDoor(){const item=state.card?.[state.door];if(!item)return;const meta=document.getElementById('promptMeta');meta.innerHTML='';if(state.door==='suggested'){[['movement',item.movement],['lens',item.lens],['depth',item.depth],['format',item.format]].forEach(([t,v])=>v&&meta.appendChild(chip(v,t)))}else if(state.door==='different'){meta.append(chip('Different Direction','movement'));if(item.lens)meta.append(chip(item.lens,'lens'))}else if(state.door==='wildcard'){meta.append(chip('Wildcard','movement'));meta.append(chip(item.format,'format'))}else meta.append(chip(state.door==='gentler'?'🌿 Gentler':'✎ Freewrite','depth'));document.getElementById('promptQuestion').textContent=item.question||'What has my attention today?';document.querySelectorAll('.door-tab').forEach(b=>{const a=b.dataset.door===state.door;b.classList.toggle('active',a);b.setAttribute('aria-selected',String(a))})}
async function openDate(iso){state.currentDate=iso;state.door='suggested';document.getElementById('todayEyebrow').textContent=iso===localIsoDate()?'JOURNAL · TODAY':'JOURNAL · PROMPT CARD';document.getElementById('todayTitle').textContent=niceDate(iso);try{state.card=await loadCard(iso);renderDoor()}catch{state.card=null;document.getElementById('promptMeta').innerHTML='';document.getElementById('promptQuestion').textContent='No Prompt Card is scheduled for this date.'}restoreChecks();go('journal');const d=document.getElementById('calendarDialog');if(d.open)d.close()}
function go(name){Object.entries(views).forEach(([k,id])=>document.getElementById(id).classList.toggle('active',k===name));document.querySelectorAll('[data-go]').forEach(b=>b.classList.toggle('active',b.dataset.go===name));window.scrollTo({top:0,behavior:'smooth'})}
function buildCalendar(){const grid=document.getElementById('calendarGrid');grid.innerHTML='';const first=new Date('2026-09-01T12:00:00').getDay();for(let i=0;i<first;i++){const e=document.createElement('span');e.className='calendar-day empty';grid.append(e)}for(let d=1;d<=30;d++){const iso=`2026-09-${String(d).padStart(2,'0')}`;const b=document.createElement('button');b.type='button';b.className='calendar-day';b.textContent=d;b.dataset.date=iso;if(iso===localIsoDate())b.classList.add('today');if(localStorage.getItem(`eolas-journal-${iso}`)==='1')b.classList.add('done');grid.append(b)}}
function chooseInitialDate(){const t=localIsoDate();return t>='2026-08-30'&&t<='2026-09-30'?t:'2026-09-01'}
function initTheme(){const saved=localStorage.getItem('eolas-theme')||'system';document.documentElement.dataset.theme=saved;document.getElementById('themeButton').title=`Appearance: ${saved}`}
function cycleTheme(){const cur=document.documentElement.dataset.theme||'system';const next=cur==='system'?'light':cur==='light'?'dark':'system';document.documentElement.dataset.theme=next;localStorage.setItem('eolas-theme',next);document.getElementById('themeButton').title=`Appearance: ${next}`}
function restoreChecks(){const iso=state.currentDate;document.getElementById('journalDone').checked=localStorage.getItem(`eolas-journal-${iso}`)==='1';document.getElementById('pixaDone').checked=localStorage.getItem(`eolas-pixa-${iso}`)==='1'}
function saveCheck(kind,checked){localStorage.setItem(`eolas-${kind}-${state.currentDate}`,checked?'1':'0');buildCalendar()}
function setZoom(v){state.zoom=Math.min(3,Math.max(.6,v));document.getElementById('zoomImage').style.transform=`scale(${state.zoom})`}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-go]');if(nav){go(nav.dataset.go);return}const door=e.target.closest('[data-door]');if(door&&state.card){state.door=door.dataset.door;renderDoor();return}const day=e.target.closest('[data-date]');if(day){openDate(day.dataset.date);return}if(e.target.closest('[data-close-calendar]'))document.getElementById('calendarDialog').close()});
document.getElementById('calendarButton').onclick=()=>document.getElementById('calendarDialog').showModal();document.getElementById('august31Button').onclick=()=>openDate('2026-08-31');document.getElementById('themeButton').onclick=cycleTheme;document.getElementById('journalDone').onchange=e=>saveCheck('journal',e.target.checked);document.getElementById('pixaDone').onchange=e=>saveCheck('pixa',e.target.checked);
const ad=document.getElementById('artifactDialog');const openArtifact=()=>{setZoom(1);ad.showModal()};document.getElementById('artifactImageButton').onclick=openArtifact;document.getElementById('atlasImageButton').onclick=openArtifact;document.getElementById('closeArtifact').onclick=()=>ad.close();document.getElementById('zoomIn').onclick=()=>setZoom(state.zoom+.25);document.getElementById('zoomOut').onclick=()=>setZoom(state.zoom-.25);document.getElementById('zoomReset').onclick=()=>setZoom(1);ad.addEventListener('click',e=>{if(e.target===ad)ad.close()});
initTheme();buildCalendar();openDate(chooseInitialDate());
